project_id = "svtaxvqlsvyseqpadjuj"

[functions.send-invite-email]
verify_jwt = false

[functions.on-user-signup]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
